config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'scrape_data', action: :scrape_data, controller: 'home'
  resources :home
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController

  def index
  end

  def scrape_data
    url = params[:url]
    return invalid_url unless UrlService.valid_url?(url)

    return not_supported_url unless url.match(ScrapeService::SITE_URL_REGEX)

    scrape_service = ScrapeService.new(url)
    cars = scrape_service.cars_list
    return no_cars_found unless cars.any?

    @message_type = 'success'
    @messages = ["#{cars.count} cars extracted"]
    @cars_table = cars.map(&method(:cars_table_format))
  end

  private

  def cars_table_format(item)
    if item.key? :car_model
      {type: 'Car Model', title: item[:car_model], price: nil}
    elsif item.key? :version_name
      {
        type: 'Car Version',
        title: item[:version_name],
        price: item[:version_price]
      }
    end
  end

  def invalid_url
    @message_type = 'danger'
    @messages = ['Invalid URL']
    render :index
  end

  def not_supported_url
    @message_type = 'danger'
    @messages = ['Provided yallamotor.com URL is not supported']
    render :index
  end

  def no_cars_found
    @message_type = 'danger'
    @messages = ['No car found']
    render :index
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<section id="search">
  <div class="container">
    <% if @messages %>
      <div class="row">
        <div class="col-12">
          <%= render partial: 'shared/alert_messages', locals: {message_type: @message_type, messages: @messages} %>
        </div>
      </div>
    <% end %>
    <div class="row my-2 spinner-row hidden" id="submit_spinner">
      <div class="col-12">
        <div class="spinner-border text-primary spinner-border-sm" role="status">
          <span class="sr-only">Loading...</span>
        </div>
        <span>Loading...</span>
      </div>
    </div>
    <div class="row">
      <div class="col-12">
        <%= form_tag(scrape_data_path, method: 'get', class: "form-inline", id: 'data-form') do %>
          <div class="input-group col-10 px-0 mb-2">
            <div class="input-group-prepend">
              <div class="input-group-text">
                <i class="fas fa-link"></i>
              </div>
            </div>
            <%= text_field_tag :url, nil, class: "form-control mr-2", placeholder: "Yallamotor URL" %>
          </div>
          <%= submit_tag "Submit", id: 'submit-btn', class: "col-2 px-0 btn btn-primary mb-2" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/home/scrape_data.html.erb
<section id="scraped-results">
  <div class="container">
    <div class="row mb-1 justify-content-end">
      <div class="col-auto">
        <%= link_to "Extract Again", root_path, class: 'btn btn-link' %>
      </div>
    </div>
    <% if @messages %>
      <div class="row">
        <div class="col-12">
          <%= render partial: 'shared/alert_messages', locals: {message_type: @message_type, messages: @messages} %>
        </div>
      </div>
    <% end %>
    <div class="container">
      <% if @cars_table.present? %>
        <div class="row">
          <div class="col-12">
            <table id="car-versions" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%;">
              <thead>
              <tr>
                <th>Type</th>
                <th>Title</th>
                <th>Price</th>
              </tr>
              </thead>
              <tbody>
              <% @cars_table.each do |car| %>
                <tr>
                  <td><%= car[:type] %></td>
                  <td><%= car[:title] %></td>
                  <td><%= car[:price] %></td>
                </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DataExtractor</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8=" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css">
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
</head>
<body id="page-top">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
  <div class="container">
    <%= link_to "Data Extractor", root_path, class: "navbar-brand js-scroll-trigger" %>
  </div>
</nav>
<header class="text-white hero-bkg-animated">
  <div class="container text-center">
    <h1>Welcome to Data Extractor</h1>
  </div>
</header>
<%= yield %>
</body>
</html>

app/views/shared/_alert_messages.html.erb
<div class="alert alert-<%= message_type %> w-100" role="alert">
  <ul class="m-0">
  	<% messages.each do |message| %>
  		<li><%= message %></li>
  	<% end %>
  </ul>
</div>